---
engines:
  tailor:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
        php:
        python:
  fixme:
    enabled: true
ratings:
  paths:
  - "**.swift"
exclude_paths: []
